development:
  adapter: postgresql
  encoding: unicode
  database: krem_parser_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: krem_parser_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: krem_parser_production
  pool: 5